#!/hint/bash

DEFAULT_MACHINE=genericx86-64
DEFAULT_DISTRO=tstick

thisdir=$(pwd)

if [[ ! -d $thisdir/meta-towelstick ]]; then
    echo "meta-towelstick not found!"
    echo "please source this script from the workspace root"
    return 1
fi
TSROOT=$(readlink -f $thisdir)
unset thisdir

if [[ -n $MACHINE ]]; then
    echo "MACHINE set to $MACHINE"
else
    echo "No MACHINE given, defaulting to $DEFAULT_MACHINE"
    MACHINE=$DEFAULT_MACHINE
fi
unset DEFAULT_MACHINE

if [[ -n $DISTRO ]]; then
    echo "DISTRO set to $DISTRO"
else
    echo "No DISTRO set, defaulting to $DEFAULT_DISTRO"
    DISTRO=$DEFAULT_DISTRO
fi
unset DEFAULT_DISTRO

if [[ -n $1 ]]; then
    BUILD_DIR="$1"
else
    BUILD_DIR="build-$MACHINE"
fi
echo "Using BUILD_DIR $BUILD_DIR"

source meta-wild-common/common-envsetup
_wild_yocto_apply_patches
_wild_yocto_symlink_cache_dir downloads
_wild_yocto_symlink_cache_dir sstate-cache


_wild_yocto_python3_hack pre
export TEMPLATECONF="$TSROOT/meta-towelstick/conf"
source openembedded-core/oe-init-build-env $BUILD_DIR
unset TEMPLATECONF BUILD_DIR
_wild_yocto_python3_hack post

# now we're in the build directory and should have bblayers.conf and local.conf
BB_CONF="conf/bblayers.conf"
LOCAL_CONF="conf/local.conf"

# post-process conf files
_wild_yocto_subst_confvars $BB_CONF $LOCAL_CONF -- TSROOT MACHINE DISTRO

unset BB_CONF LOCAL_CONF TSROOT MACHINE DISTRO
_wild_yocto_unset_functions
